By using regression

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [ ]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()       # keras randomly w initialize krta h

[array([[0.48476124, 0.51203036],
        [0.55187464, 0.1987158 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.8149208],
        [-1.2233834]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error", optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 31.1240  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.9299 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.0619 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7381 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1490 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.0442 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.4613 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.2012 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.1252 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6300 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.1847 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.6052 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.1786 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.5860 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.3705 
Epoch 16/75
4/4 ━━

In [ ]:
model.get_weights()

[array([[0.3738055, 0.3738055],
        [0.3655995, 0.3655995]], dtype=float32),
 array([0.27239957, 0.27239957], dtype=float32),
 array([[0.37299564],
        [0.37299564]], dtype=float32),
 array([0.2047419], dtype=float32)]

ab yha s apna code likha tha jo ki manually krre h upr me lib k help s hua h

In [ ]:
# 1.
# total w = 6, b = 3.....value taken for w is 0.1 and b is 0
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1, L):

        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters

In [ ]:
initialize_parameters([2,2,1])
# ye neural network ka architecture h 2 nodes, 2 nodes, 1 node
# w1 me 4 aayega weights aayega, w2 me pjr 2 aayega, b1 me 2 node h n, b2 me last node

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev, W, b):     # previous layer s jo mil rha h aur jo w aur b h
    Z = np.dot(W.T, A_prev) + b

    return Z
# linear forward kisi b given neuron(node) ka o/p calculate krega
# a given neruon(node) depends on 5 things weights, i/p it is getting, uska khuka bias aur bias teen milega qki 3 node

In [ ]:
# main function for forward propagation
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2                # no. of layers in the neural network

    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        # print("A" + str(l-1) + ": ", (A_prev))
        # print("W" + str(l) + ": ", (Wl))
        # print("b" + str(l) + ": ", (bl))
        # print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        # print("A" + str(l) + ": ", (A))
        # print("**"*20)

    return A, A_prev

# 1st student ko uthakr L_layer me bhejo sth me parameters h jo upr aaya
# ye A aur a ka previous isiliye return krra h qki for next steps we need those previous one also

In [ ]:
from re import L
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no. of features, no. of training example)
y = df[['lpa']].values[0][0]

# parameter initialization
parameters = initialize_parameters([2,2,1])
# sbko bs x,y aur parameters me store kr liya h

y_hat,A1 = L_layer_forward(X, parameters)

# A[O] = [8,8] h then w and b k basis pr
# A[1] = [O11,O12] h then w and b k basis pr
# A[2] = [O21] h

In [ ]:
y_hat = y_hat[0][0]

In [ ]:
# 3. loss function
(y - 0.32)**2

13.5424

In [ ]:
A1

array([[1.6],
       [1.6]])

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)    # niche wale ko run krke jb isko run krenge to parameters change hogye h

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [ ]:
from re import L
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no. of features, no. of training example)
y = df[['lpa']].values[2][0]

# parameter initialization
# parameters = initialize_parameters([2,2,1])
# sbko bs x,y aur parameters me store kr liya h

y_hat,A1 = L_layer_forward(X, parameters)    # y_hat for 2nd student

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)
# again parameters got changed
# 2 baar aur krna for 3rd and 4th student to iss baar wai pr change kr denge

<ipython-input-17-5fc9316c58fa>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-17-5fc9316c58fa>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-17-5fc9316c58fa>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

{'W1': array([[0.1137888, 0.1238792],
        [0.1137888, 0.1238792]]),
 'b1': array([[0.00226416],
        [0.00226416]]),
 'W2': array([[0.13162741],
        [0.13162741]]),
 'b2': array([[0.14257867]])}

In [ ]:
# 4. update w and b using Wn
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

  return parameters

# 9 updates lega jo pehle aaya tha n differentiate krke

In [ ]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no. of features, no  of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())    # uss particular epoch me jitta b loss hua h wo print hojaye aur sbse end me loop s bahr nikl kr print horha h

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}